/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FrameworksRouteImport } from './routes/frameworks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas/index'
import { Route as IdeasNewRouteImport } from './routes/ideas/new'
import { Route as IdeasIdRouteImport } from './routes/ideas/$id'

const FrameworksRoute = FrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasNewRoute = IdeasNewRouteImport.update({
  id: '/ideas/new',
  path: '/ideas/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/frameworks': typeof FrameworksRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/frameworks': typeof FrameworksRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/frameworks': typeof FrameworksRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas/new': typeof IdeasNewRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/frameworks' | '/ideas/$id' | '/ideas/new' | '/ideas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/frameworks' | '/ideas/$id' | '/ideas/new' | '/ideas'
  id: '__root__' | '/' | '/frameworks' | '/ideas/$id' | '/ideas/new' | '/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrameworksRoute: typeof FrameworksRoute
  IdeasIdRoute: typeof IdeasIdRoute
  IdeasNewRoute: typeof IdeasNewRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/frameworks': {
      id: '/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof FrameworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/new': {
      id: '/ideas/new'
      path: '/ideas/new'
      fullPath: '/ideas/new'
      preLoaderRoute: typeof IdeasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrameworksRoute: FrameworksRoute,
  IdeasIdRoute: IdeasIdRoute,
  IdeasNewRoute: IdeasNewRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
